"""Initial migration.

Revision ID: d5d719bb80a4
Revises: 
Create Date: 2022-04-07 21:17:28.843597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d719bb80a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_type')
    )
    op.create_table('inv_resp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inv_resp_type', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inv_resp_type')
    )
    op.create_table('month',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_name', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month_name')
    )
    op.create_table('ta_officer',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sla_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('per_year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['month'], ['month.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('per_year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['month'], ['month.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('officer_code', sa.String(length=3), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('access_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_id'], ['access.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('officer_code')
    )
    op.create_table('relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('portfolio_manager', sa.String(length=5), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('call_sla', sa.Integer(), nullable=True),
    sa.Column('meeting_sla', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['call_sla'], ['sla_call.id'], ),
    sa.ForeignKeyConstraint(['meeting_sla'], ['sla_meeting.id'], ),
    sa.ForeignKeyConstraint(['portfolio_manager'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('update_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=5), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('who_updated', sa.String(length=5), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationship.id'], ),
    sa.ForeignKeyConstraint(['who_updated'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lma_account',
    sa.Column('accountnumber', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=30), nullable=False),
    sa.Column('trust_advisor', sa.String(length=3), nullable=False),
    sa.Column('portfolio_manager', sa.String(length=5), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('invest_resp', sa.Integer(), nullable=False),
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invest_resp'], ['inv_resp.id'], ),
    sa.ForeignKeyConstraint(['portfolio_manager'], ['user.id'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationship.id'], ),
    sa.ForeignKeyConstraint(['trust_advisor'], ['ta_officer.code'], ),
    sa.ForeignKeyConstraint(['update_id'], ['update_account.id'], ),
    sa.PrimaryKeyConstraint('accountnumber'),
    sa.UniqueConstraint('account_name')
    )
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('who_updated', sa.String(length=5), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationship.id'], ),
    sa.ForeignKeyConstraint(['who_updated'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sma_account',
    sa.Column('accountnumber', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=30), nullable=False),
    sa.Column('trust_advisor', sa.String(length=3), nullable=False),
    sa.Column('portfolio_manager', sa.String(length=5), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('invest_resp', sa.Integer(), nullable=False),
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('lma_account', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invest_resp'], ['inv_resp.id'], ),
    sa.ForeignKeyConstraint(['lma_account'], ['lma_account.accountnumber'], ),
    sa.ForeignKeyConstraint(['portfolio_manager'], ['user.id'], ),
    sa.ForeignKeyConstraint(['trust_advisor'], ['ta_officer.code'], ),
    sa.ForeignKeyConstraint(['update_id'], ['update_account.id'], ),
    sa.PrimaryKeyConstraint('accountnumber'),
    sa.UniqueConstraint('account_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sma_account')
    op.drop_table('meeting')
    op.drop_table('lma_account')
    op.drop_table('call')
    op.drop_table('update_account')
    op.drop_table('relationship')
    op.drop_table('user')
    op.drop_table('sla_meeting')
    op.drop_table('sla_call')
    op.drop_table('ta_officer')
    op.drop_table('month')
    op.drop_table('inv_resp')
    op.drop_table('access')
    # ### end Alembic commands ###
